export const DEFAULT_NUMBER_OF_ANSWERS = 4;

export enum LOCALES {
  UK = 'uk',
  RU = 'ru',
  EN = 'en'
}

export enum FOOD_CATEGORIES {
  RANDOM = 'RANDOM',
  SUSHI = 'SUSHI',
  PIZZA = 'PIZZA',
  SHAWERMA = 'SHAWERMA',
  VEGETARIAN = 'VEGETARIAN',
  NOODLES_N_RICE = 'NOODLES_N_RICE',
  HOMEY = 'HOMEY',
  BURGERS = 'BURGERS',
  HOTDOGS = 'HOTDOGS',
  SANDWICHES = 'SANDWICHES',
  SALADS = 'SALADS',
  SOUPS = 'SOUPS',
  PASTA = 'PASTA',
  SNACKS = 'SNACKS',
  DESSERTS = 'DESSERTS',
  CHILDREN_MENU = 'CHILDREN_MENU'
}

export enum KITCHEN_CATEGORIES {
  RANDOM = 'RANDOM',
  HOMEY = 'HOMEY',
  UKRAINIAN = 'UKRAINIAN',
  EAST = 'EAST',
  ITALIAN = 'ITALIAN',
  EUROPEAN = 'EUROPEAN',
  AMERICAN = 'AMERICAN',
  JAPANESE = 'JAPANESE',
  CHINESE = 'CHINESE',
  KOREAN = 'KOREAN',
  GEORGIAN = 'GEORGIAN',
  THAI = 'THAI',
  MEXICAN = 'MEXICAN'
}

export enum SUPPORTED_CITIES {
  OTHER = 'other',
  ODESA = 'odesa',
  // KYIV = 'kyiv'
}

export enum USER_STATES {
  WAIT_FOR_LOCATION = 'WAIT_FOR_LOCATION',
  WAIT_FOR_TEXT_CITY_OTHER = 'WAIT_FOR_TEXT_CITY_OTHER',
  WAIT_FOR_SECTION = 'WAIT_FOR_SECTION',
  WAIT_FOR_FEEDBACK = 'WAIT_FOR_FEEDBACK',
  WAIT_FOR_KITCHEN = 'WAIT_FOR_KITCHEN',
  WAIT_FOR_FOOD_CATEGORY = 'WAIT_FOR_FOOD_CATEGORY',
  WAIT_FOR_REPEAT_OR_RESTART = 'WAIT_FOR_REPEAT_OR_RESTART',
  WAIT_FOR_CITY_CONFIRM = 'WAIT_FOR_CITY_CONFIRM',
}

export enum SECTIONS {
  LUCKY = 'LUCKY',
  FOOD = 'FOOD',
  KITCHEN = 'KITCHEN'
}
