export const DEFAULT_NUMBER_OF_ANSWERS = 5;

export enum LOCALES {
  UK = 'uk',
  RU = 'ru',
  EN = 'en'
}

export enum FOOD_CATEGORIES {
  RANDOM = 'RANDOM',
  SUSHI = 'SUSHI',
  PIZZA = 'PIZZA',
  SHAWERMA = 'SHAWERMA',
  VEGETARIAN = 'VEGETARIAN',
  NOODLES_N_RICE = 'NOODLES_N_RICE',
  HOMEY = 'HOMEY',
  BURGERS = 'BURGERS',
  HOTDOGS = 'HOTDOGS',
  SANDWICHES = 'SANDWICHES',
  SALADS = 'SALADS',
  SOUPS = 'SOUPS',
  PASTA = 'PASTA',
  SNACKS = 'SNACKS',
  DESSERTS = 'DESSERTS',
  CHILDREN_MENU = 'CHILDREN_MENU'
}

export enum KITCHEN_CATEGORIES {
  RANDOM = 'RANDOM',
  HOMEY = 'HOMEY',
  UKRAINIAN = 'UKRAINIAN',
  EAST = 'EAST',
  ITALIAN = 'ITALIAN',
  EUROPEAN = 'EUROPEAN',
  AMERICAN = 'AMERICAN',
  JAPANESE = 'JAPANESE',
  CHINESE = 'CHINESE',
  KOREAN = 'KOREAN',
  GEORGIAN = 'GEORGIAN',
  THAI = 'THAI',
  MEXICAN = 'MEXICAN'
}
